name: Update README

on:
  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt
      - name: Run update script
        run: python3 update_keybinds.py
      - name: Commit and push changes
        run: |
          git config --global user.name "gitea-actions[bot]"
          git config --global user.email "gitea-actions[bot]@users.noreply.objectmanip.net"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README.md"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITEA_TOKEN }}
